@startuml

title ** Tienda Online **

"Abstract Factory" -[hidden]u- TiendOnline
package "Abstract Factory" #DDDDDD {
   'Clases'
   interface AbstractFactory{
     + createWebcam()
     + createHeadset()
     + createTeclado()
     + createMouse()
   }
   
   
   interface webcam{}
   interface headset{}
   interface teclado{}
   interface mouse{}


    'Relaciones'
   
   AbstractFactory <|.u. createFactoryStarter
   AbstractFactory <|.d. createFactoryPlatinum
   AbstractFactory <|.l. createFactoryGold

   webcam <|.u. webcamStarter
   webcam <|.d. webcamPlatinum
   webcam <|.d. webcamGold

   headset <|.u. headsetStarter
   headset <|.d. headsetPlatinum
   headset <|.d. headsetGold

   teclado <|.u. tecladoStarter
   teclado <|.d. tecladoPlatinum
   teclado <|.d. tecladoGold
   
   mouse <|.u. mouseStarter
   mouse <|.d. mousePlatinum
   mouse <|.d. mouseGold
}

@enduml